### ISSUE TITLE
orks are not working :S

### ISSUE THREAD

**Issue by Fwaffle** [BSData/wh40k-7th-edition#189]
Errors occurred updating data files from repositories
    > https://github.com/BSData/wh40k/blob/master/Orks%20-%20Codex.cat: Error updating from repository https://github.com/BSData/wh40k/blob/master/Orks%20-%20Codex.cat: data.CorruptDataException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
    at gui.common.UpdateDataFilesDialog$1.a(Unknown Source)
    at gui.common.UpdateDataFilesDialog$1.doInBackground(Unknown Source)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
idk y this keeps happening what is wrong?

**Comment by amis92** [comment]
To be honest I think it's a bug in BattleScribe. I'd report it on it's UserVoice page: http://battlescribe.uservoice.com/forums/55066-general

**Comment by Jonskichov** [comment]
@Fwaffle Can you tell me if you are still having this problem? Make sure you are using BattleScribe 1.14.05.

**Comment by amis92** [comment]
No movement here. Closing.
