### ISSUE TITLE
cult mech & skitarii roster creation error on windows battlescribe

### ISSUE THREAD

**Issue by laurent-conte** [BSData/wh40k-7th-edition#2708]
I have the latest version of battlescribe, and updated the database.

Now I have error whenever I try to create any mechanicum or skitarii roster.

I unistalled/reinstalled battlescribe many times without improvements.

Details:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> Skitarii: Codex (2015):2301-1cab-6d58-f23b:net.battlescribe.model.data.Catalogue@542818a6: The catalogue data file is invalid:
> AdM Skitarii Maniple:266d-6369-fcc2-e8f6:net.battlescribe.model.data.ForceEntry@522c2e13: All ForceEntries in a Catalogue must have unique names
> e4f2-353c-28e2-ce5e:net.battlescribe.model.data.InfoLink@29f6597d: Link must have a target that exists
> d763-57c1-5436-0a8d:net.battlescribe.model.data.InfoLink@17184e48: Link must have a target that exists
> f2da-0395-3dec-612d:net.battlescribe.model.data.InfoLink@57b81e51: Link must have a target that exists
> 1bc8-0dc5-930a-7177:net.battlescribe.model.data.InfoLink@11b0c6b8: Link must have a target that exists
> cd50-3bdc-d759-f892:net.battlescribe.model.data.InfoLink@670ae732: Link must have a target that exists
> 130c-80dc-83f7-0aac:net.battlescribe.model.data.InfoLink@477c34a6: Link must have a target that exists
> 90b2-c5ae-0ce5-aa92:net.battlescribe.model.data.InfoLink@d63733a: Link must have a target that exists
> f547-abd6-972c-71ec:net.battlescribe.model.data.InfoLink@75b68031: Link must have a target that exists
> New InfoLink:02a1-76e7-d8e2-0193:net.battlescribe.model.data.InfoLink@a578014: Link must have a target that exists
> bc12-88ac-677b-1643:net.battlescribe.model.data.InfoLink@2cc5e1c3: Link must have a target that exists
> 6a15-81f5-99b2-1f56:net.battlescribe.model.data.InfoLink@45de3c2: Link must have a target that exists
> b3be-16a9-af44-481e:net.battlescribe.model.data.InfoLink@12637bcf: Link must have a target that exists
> dab2-03fa-0926-5ba9:net.battlescribe.model.data.InfoLink@7173d743: Link must have a target that exists
> 9c6c-09c7-18fa-de1f:net.battlescribe.model.data.InfoLink@5a21beba: Link must have a target that exists
> 2c31-e95a-4776-b1b7:net.battlescribe.model.data.InfoLink@7f463242: Link must have a target that exists
> 17af-35c6-32e4-6744:net.battlescribe.model.data.InfoLink@22736e1a: Link must have a target that exists
> f636-8bb1-b675-32c1:net.battlescribe.model.data.InfoLink@6f3bcc50: Link must have a target that exists
> 21ed-ee8f-672e-6754:net.battlescribe.model.data.InfoLink@231f7f79: Link must have a target that exists
> a576-9e24-aae3-3758:net.battlescribe.model.data.InfoLink@78e652a7: Link must have a target that exists
> f3af-d642-135e-5c13:net.battlescribe.model.data.InfoLink@3d20fb4: Link must have a target that exists
> cac5-d23d-629a-c12f:net.battlescribe.model.data.InfoLink@4512659e: Link must have a target that exists
> 3bb6-68b0-54df-e41f:net.battlescribe.model.data.InfoLink@374a4106: Link must have a target that exists
> cfbf-1387-9d5a-caed:net.battlescribe.model.data.InfoLink@579ecb55: Link must have a target that exists
> 6857-ab36-e1b6-ac65:net.battlescribe.model.data.InfoLink@4b56ac93: Link must have a target that exists
> 9f1e-a465-edc3-f579:net.battlescribe.model.data.InfoLink@7543f40b: Link must have a target that exists
> fbf2-f956-c61d-0d7b:net.battlescribe.model.data.InfoLink@11c05e20: Link must have a target that exists
> 266d-da54-b10a-3918:net.battlescribe.model.data.InfoLink@3c774412: Link must have a target that exists
> 18b4-504a-a702-8fdb:net.battlescribe.model.data.InfoLink@7d71b53c: Link must have a target that exists
> 9946-8be4-9cd4-6ecb:net.battlescribe.model.data.InfoLink@58a2b3be: Link must have a target that exists
> 094b-e4d9-b670-d505:net.battlescribe.model.data.InfoLink@38c9a764: Link must have a target that exists
> 82c8-aa5d-0f22-1271:net.battlescribe.model.data.InfoLink@6cebd985: Link must have a target that exists
> 21fc-0f67-bbe9-6912:net.battlescribe.model.data.InfoLink@16676cd7: Link must have a target that exists
> 84ca-8d56-1682-e91b:net.battlescribe.model.data.InfoLink@27d24f03: Link must have a target that exists
> 4fa2-4b8e-674d-6270:net.battlescribe.model.data.InfoLink@145edfe6: Link must have a target that exists
> 7aa0-1b96-6da3-612c:net.battlescribe.model.data.InfoLink@3014dddc: Link must have a target that exists
> a17a-b407-970d-c1a8:net.battlescribe.model.data.InfoLink@667b11f2: Link must have a target that exists
> b2a1-1d3c-c6e6-e7f0:net.battlescribe.model.data.InfoLink@4384334: Link must have a target that exists
> ed54-5b4e-c702-a90c:net.battlescribe.model.data.InfoLink@29c6d15c: Link must have a target that exists
> e1cf-bc54-4eb0-be92:net.battlescribe.model.data.InfoLink@64930ec4: Link must have a target that exists
> 9e1a-b188-5c72-52dc:net.battlescribe.model.data.InfoLink@464ebbd0: Link must have a target that exists
> New InfoLink:1f75-6344-c211-c528:net.battlescribe.model.data.InfoLink@4cc98de0: Link must have a target that exists
> 5f49-734e-4016-1317:net.battlescribe.model.data.InfoLink@117eecbb: Link must have a target that exists
> New InfoLink:3d33-79d2-162f-4452:net.battlescribe.model.data.InfoLink@456947c4: Link must have a target that exists
> c923-f8a8-e99c-c872:net.battlescribe.model.data.InfoLink@2aa416b8: Link must have a target that exists
> 7da1-4613-47c4-10e5:net.battlescribe.model.data.InfoLink@2a477e96: Link must have a target that exists
> New InfoLink:9dde-beaf-f663-1938:net.battlescribe.model.data.InfoLink@48244eb3: Link must have a target that exists
> New InfoLink:950f-9b91-55ba-1e59:net.battlescribe.model.data.InfoLink@42447590: Link must have a target that exists
> New InfoLink:bbb6-f54f-0559-144a:net.battlescribe.model.data.InfoLink@10921ae6: Link must have a target that exists
> New InfoLink:6989-7538-12de-0411:net.battlescribe.model.data.InfoLink@21317bec: Link must have a target that exists
> New InfoLink:e284-7e73-0c9a-2992:net.battlescribe.model.data.InfoLink@4b8ae8af: Link must have a target that exists
> New InfoLink:3e7d-3ec7-e289-5c39:net.battlescribe.model.data.InfoLink@2a03fcbb: Link must have a target that exists
> c4bb-0b3c-5aad-fa90:net.battlescribe.model.data.InfoLink@3167f686: Link must have a target that exists
> 6629-2e2f-96d5-b79a:net.battlescribe.model.data.InfoLink@23ed0fd: Link must have a target that exists
> 1edb-59e4-8197-3921:net.battlescribe.model.data.InfoLink@5709187: Link must have a target that exists
> dfb0-ead0-557d-196f:net.battlescribe.model.data.InfoLink@607386f1: Link must have a target that exists
> a0a2-0a3f-2e60-947e:net.battlescribe.model.data.InfoLink@5ebe6fac: Link must have a target that exists
> 7fce-97f3-fbd2-8c6d:net.battlescribe.model.data.InfoLink@e968fea: Link must have a target that exists
> b9d5-0617-b5e8-f60c:net.battlescribe.model.data.InfoLink@3d94859a: Link must have a target that exists
> 0674-42ef-cdf4-b73a:net.battlescribe.model.data.InfoLink@1cf50dc3: Link must have a target that exists
> 27ad-4227-7a04-e680:net.battlescribe.model.data.InfoLink@31615e7a: Link must have a target that exists
> 540d-5f9b-48ad-e6aa:net.battlescribe.model.data.InfoLink@7b82e143: Link must have a target that exists
> 385a-ad6c-b9f1-8ce5:net.battlescribe.model.data.InfoLink@258bbbfc: Link must have a target that exists
> 7540-9821-89a8-99cd:net.battlescribe.model.data.InfoLink@68be80bb: Link must have a target that exists
> e67e-deae-5420-9a1a:net.battlescribe.model.data.InfoLink@45cf1385: Link must have a target that exists
> New InfoLink:be58-989f-fa79-b14b:net.battlescribe.model.data.InfoLink@136b2aef: Link must have a target that exists
> 9236-b98d-688b-ba70:net.battlescribe.model.data.InfoLink@1c059175: Link must have a target that exists
> 845d-1329-32b7-29ce:net.battlescribe.model.data.InfoLink@4cea6e07: Link must have a target that exists
> acd2-9664-10b8-c12e:net.battlescribe.model.data.InfoLink@81f4310: Link must have a target that exists
> 9e89-469d-7d2a-82d0:net.battlescribe.model.data.InfoLink@3654c74e: Link must have a target that exists
> 10d7-f809-e331-7363:net.battlescribe.model.data.InfoLink@41dbf490: Link must have a target that exists
> New InfoLink:e546-1a31-6c3b-0d1a:net.battlescribe.model.data.InfoLink@3b5fff14: Link must have a target that exists
> New InfoLink:a58b-0709-ff45-47cd:net.battlescribe.model.data.InfoLink@6ef35872: Link must have a target that exists
> fa4c-b50d-1368-025a:net.battlescribe.model.data.InfoLink@4241d4ac: Link must have a target that exists
> 811e-b9ba-03f6-87c2:net.battlescribe.model.data.InfoLink@5032d1b8: Link must have a target that exists
> 31dc-440e-6a4e-de49:net.battlescribe.model.data.InfoLink@1c9a9ba6: Link must have a target that exists
> e572-b064-fba1-b9f1:net.battlescribe.model.data.InfoLink@51a4b952: Link must have a target that exists
> 2098-599e-e1b8-3e9e:net.battlescribe.model.data.InfoLink@23e892bc: Link must have a target that exists
> 2d88-2e3b-9473-a4c6:net.battlescribe.model.data.InfoLink@7c929e80: Link must have a target that exists
> 0702-408a-105d-1997:net.battlescribe.model.data.InfoLink@5a419d19: Link must have a target that exists
> 41e7-b6e4-2836-083d:net.battlescribe.model.data.InfoLink@271738ae: Link must have a target that exists
> 9a3e-9730-caa0-7524:net.battlescribe.model.data.InfoLink@339ff3a3: Link must have a target that exists
> b298-0272-b204-4b4b:net.battlescribe.model.data.InfoLink@17170308: Link must have a target that exists
> c2ca-88e7-7b4d-5757:net.battlescribe.model.data.InfoLink@75cf9be7: Link must have a target that exists
> 5792-9148-6969-13a9:net.battlescribe.model.data.InfoLink@349bfa4: Link must have a target that exists
> 0582-c846-de61-2a76:net.battlescribe.model.data.InfoLink@a501c89: Link must have a target that exists
> e818-c9d2-7c09-f949:net.battlescribe.model.data.InfoLink@79b8f14: Link must have a target that exists
> 491a-ee51-20fc-2eb0:net.battlescribe.model.data.InfoLink@4e6d2228: Link must have a target that exists
> d0af-4b84-4f0c-17da:net.battlescribe.model.data.InfoLink@18c7319f: Link must have a target that exists
> 8398-835f-9371-839e:net.battlescribe.model.data.InfoLink@105166d1: Link must have a target that exists
> 29ae-f990-425a-5162:net.battlescribe.model.data.InfoLink@40856b51: Link must have a target that exists
> New InfoLink:3c74-53ed-c48d-52fa:net.battlescribe.model.data.InfoLink@3df9cc8d: Link must have a target that exists
> 285d-5832-8951-b5a9:net.battlescribe.model.data.InfoLink@6e8a3101: Link must have a target that exists
> 5cde-9d95-a0fa-14b4:net.battlescribe.model.data.InfoLink@55e27b9c: Link must have a target that exists
> New InfoLink:9039-92ac-69b5-324f:net.battlescribe.model.data.InfoLink@39f86c83: Link must have a target that exists
> c800-3537-1d07-05f2:net.battlescribe.model.data.InfoLink@57567862: Link must have a target that exists
> d1fa-8757-66a7-1179:net.battlescribe.model.data.InfoLink@6069b900: Link must have a target that exists
> 35dc-0522-da4f-4157:net.battlescribe.model.data.InfoLink@6e9102e1: Link must have a target that exists
> 2c0a-a894-3729-3110:net.battlescribe.model.data.InfoLink@3a050739: Link must have a target that exists
> 60b0-083e-1d07-809f:net.battlescribe.model.data.InfoLink@7b846807: Link must have a target that exists
> f47d-6c33-c151-3335:net.battlescribe.model.data.InfoLink@189a19d1: Link must have a target that exists
> cd19-c9e9-b20b-42a8:net.battlescribe.model.data.InfoLink@2e2a5499: Link must have a target that exists
> e919-fbe1-b9c4-a6e7:net.battlescribe.model.data.InfoLink@2f812c74: Link must have a target that exists
> New InfoLink:05de-cb99-37df-5b65:net.battlescribe.model.data.InfoLink@5fa5ba5c: Link must have a target that exists
> New InfoLink:ab00-d68b-9fde-9e18:net.battlescribe.model.data.InfoLink@2357b3ad: Link must have a target that exists
> c68b-258e-fd88-745e:net.battlescribe.model.data.InfoLink@394478ff: Link must have a target that exists
> 18b8-1c12-bd78-b190:net.battlescribe.model.data.InfoLink@2499cd3: Link must have a target that exists
> New InfoLink:12bc-df99-b914-294e:net.battlescribe.model.data.InfoLink@4ed0350: Link must have a target that exists
> 80d8-aad8-d51d-574f:net.battlescribe.model.data.InfoLink@4c72404a: Link must have a target that exists
> New InfoLink:ed0e-fb9b-be8c-98e9:net.battlescribe.model.data.InfoLink@1b48ac62: Link must have a target that exists
> New InfoLink:48eb-d460-3ed5-fc61:net.battlescribe.model.data.InfoLink@606ac5ff: Link must have a target that exists
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.a(BattleScribe:698)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.a(BattleScribe:579)
	at net.battlescribe.desktop.rostereditor.f.i(BattleScribe:314)
	at net.battlescribe.desktop.rostereditor.f.b(BattleScribe:478)
	at net.battlescribe.desktop.rostereditor.f.b(BattleScribe:37)
	at net.battlescribe.desktop.rostereditor.f$3.actionPerformed(BattleScribe:375)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.W(BattleScribe:1702)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.f(BattleScribe:3128)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame.i(BattleScribe:74)
	at net.battlescribe.desktop.rostereditor.RosterEditorFrame$9.actionPerformed(BattleScribe:2396)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Thairne** [comment]
Version of Battlescribe?
Version of Skitarii datafile?
Creating a Skitarii Maniple?

I've just today created a list with a DWSF, RWSF and a Skitarii Maniple and it worked just fine.

**Comment by laurent-conte** [comment]
Forget it... I just find out the data were not on program files/battlescribe but on the user profile... I deleted all and reuploaded the database... it s all good now... sorry to bother!

**Comment by Thairne** [comment]
:)
