### ISSUE TITLE
Repository is corrupt

### ISSUE THREAD

**Issue by HelixShade** [BSData/wh40k-7th-edition#6]
Keep seeing the following error when I attempt to download the WH40K repository.

```
"BattleScribe failed to download and import one or more data files from the repository.
    > model.dataindex.DataIndexEntry@7a1f99: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Warhammer40K.gstz
    > model.dataindex.DataIndexEntry@1b0b39a: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Knights%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@1df50a3: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Eldar%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@270dad: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Dark%20Eldar%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@1f3198f: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Legion%20of%20the%20Damned%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@11316f4: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Tau%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@482417: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Guard%20-%20FW%20-%20Vraks%20Renegades.catz
    > model.dataindex.DataIndexEntry@397bcb: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Necrons%20-%20FW%20-%20Dark%20Harvest.catz
    > model.dataindex.DataIndexEntry@1ee5bed: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Space%20Marines%20-%20FW%20-%20Tyrant's%20Legion.catz
    > model.dataindex.DataIndexEntry@1d54d9a: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Adepta%20Sororitas%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@d9ceea: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Guard%20-%20FW%20-%20Death%20Korps%20Siege.catz
    > model.dataindex.DataIndexEntry@19f9f8e: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Space%20Marines%20-%20Supplement%20-%20Sentinels%20of%20Terra.catz
    > model.dataindex.DataIndexEntry@a44130: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Space%20Marines%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@1b3c607: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Space%20Wolves%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@18e0f0f: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Blood%20Angels%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@17eaaca: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/30K%20-%20Horus%20Heresy.catz
    > model.dataindex.DataIndexEntry@feb697: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Tyranids%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@8593d0: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Space%20Marines%20-%20Supplement%20-%20Clan%20Raukaan.catz
    > model.dataindex.DataIndexEntry@1ab5fd5: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Dark%20Angels%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@20a82a: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Guard%20-%20FW%20-%20Elysians.catz
    > model.dataindex.DataIndexEntry@8dad: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Eldar%20-%20FW%20-%20Corsairs.catz
    > model.dataindex.DataIndexEntry@557280: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Inquisition%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@1d05385: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Fortifications%20and%20Stronghold%20Assault.catz
    > model.dataindex.DataIndexEntry@1b7e37: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Chaos%20Daemons%20(40K)%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@fb541d: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Chaos%20Space%20Marines%20-%20Supplement%20-%20Crimson%20Slaughter.catz
    > model.dataindex.DataIndexEntry@4f5403: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Chaos%20Space%20Marines%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@14cda3: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Guard%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@1c8b26e: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Chaos%20Space%20Marines%20-%20Supplement%20-%20Black%20Legion.catz
    > model.dataindex.DataIndexEntry@13a7ebb: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Astra%20Militarum%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@15635fa: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Eldar%20-%20Supplement%20-%20Iyanden.catz
    > model.dataindex.DataIndexEntry@f1e723: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Guard%20-%20Apocalypse.catz
    > model.dataindex.DataIndexEntry@17de0a8: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Tau%20-%20Supplement%20-%20Farsight%20Enclaves.catz
    > model.dataindex.DataIndexEntry@1286799: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Necrons%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@1a97595: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Orks%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@669c84: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Imperial%20Guard%20-%20FW%20-%20Death%20Korps%20Assault.catz
    > model.dataindex.DataIndexEntry@adaa9f: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Space%20Marines%20-%20FW%20-%20Siege%20Assault%20Vanguard.catz
    > model.dataindex.DataIndexEntry@19cea9e: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Militarum%20Tempestus%20-%20Codex.catz
    > model.dataindex.DataIndexEntry@ef54ee: http://battlescribedata.appspot.com/repos/wh40k/Space%20Marines%20-%20Codex.catz/repos/wh40k/Grey%20Knights%20-%20Codex.catz
    at data.ImportUtils.a(Unknown Source)
    at data.ImportUtils.importDataFile(Unknown Source)
    at gui.common.GuiUtils.a(Unknown Source)
    at gui.common.GuiUtils.importDataFromFile(Unknown Source)
    at gui.common.ManageDataDialog$4.a(Unknown Source)
    at gui.common.ManageDataDialog$4.doInBackground(Unknown Source)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)"
```

Battlescribe version is 1.14.00b.

**Comment by amis92** [comment]
@Jonskichov , investigating? Is this repo or BS?

**Comment by HelixShade** [comment]
BS. FINALLY got it to work somehow, I'm not sure how though beyond it
finally deciding to work.

**Comment by Jonskichov** [comment]
@amis92 @HelixShade I suspect a teething problem with the site - it's new and is starting to see heavier use after all. Also I deployed the site multiple times today so might be related.

I'll check the logs tomorrow. Glad it started working though.

**Comment by Jonskichov** [comment]
@HelixShade I've taken a look through the logs and fixed a couple of things that came up overnight. It's hard to say if any of them were your particular issue though. We'll keep an eye on things.

**Comment by HelixShade** [comment]
Or not so much. Got this Error as BattleScribe was just booting up -

"Errors occurred updating data files from repositories

> http://battlescribedata.appspot.com/repos/wh40k/index.bsi: Error updating
> from repository http://battlescribedata.appspot.com/repos/wh40k/index.bsi:
> java.io.IOException: Server returned HTTP response code: 503 for URL:
> http://battlescribedata.appspot.com/repos/wh40k/index.bsi
> at gui.common.UpdateDataFilesDialog$1.a(Unknown Source)
> at gui.common.UpdateDataFilesDialog$1.doInBackground(Unknown Source)
> at javax.swing.SwingWorker$1.call(Unknown Source)
> at java.util.concurrent.FutureTask.run(Unknown Source)
> at javax.swing.SwingWorker.run(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.lang.Thread.run(Unknown Source)"

Fortunately, the roster still works, but it seems it's created a hiccup X3

**Comment by Jonskichov** [comment]
Ah that's a bandwidth issue... Looks like the site has gotten rather popular rather quickly... :S

**Comment by Toreador13** [comment]
Yeah, I use quite a bit of bandwidth from the FTP every month. Looks like this repo is out already for the month. Kind of odd, because my work machine now no longer seems to see the dropbox datafiles either. Going to have to go through and redo that to see if it recognizes it again. Right now it just keeps taking me to the Start Page.

**Comment by Jonskichov** [comment]
@Toreador is that for Randomhit? Things have been really popular since the recent BattleScribe release, so maybe you've had extra visitors? Though I was able to get to the forum.

Thankfully the appspot/App Engine service the date site is on has a daily quota so it's back up now. I put in some fixes for the problem we were having and it all looks good now. See: https://github.com/BSData/bsdata/issues/25

We'll be monitoring the situation. Hopefully we won't have to upgrade to a paid account ;-)

**Comment by Jonskichov** [comment]
@HelixShade @Amis92 I'm going to close this issue in favour of https://github.com/BSData/bsdata/issues/25

I think the problem is resolved but will continue to monitor.

If anyone has further comments please post on the other issue.
